2025-03-09 03:44:09,178 INFO    MainThread:3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:09,178 INFO    MainThread:3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:09,178 INFO    MainThread:3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:09,178 INFO    MainThread:3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034409-d480lmis/logs/debug.log
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034409-d480lmis/logs/debug-internal.log
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'use_wandb': 'true', 'wandb_project': 'ns24z274_da6401_assignment1', 'wandb_entity': 'ns24z274-iitm-ac-in', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 4, 'loss': 'cross_entropy', 'optimizer': 'sgd', 'learning_rate': 0.01, 'momentum': 0.5, 'beta': 0.5, 'beta1': 0.5, 'beta2': 0.5, 'epsilon': 1e-06, 'weight_decay': 0.0, 'weight_init': 'Xavier', 'num_layers': 3, 'hidden_size': 128, 'activation': 'sigmoid', 'gradient_clip_w': 1.0, 'gradient_clip_b': 1.0, '_wandb': {}}
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_init.py:init():784] starting backend
2025-03-09 03:44:09,179 INFO    MainThread:3619015 [wandb_init.py:init():788] sending inform_init request
2025-03-09 03:44:09,181 INFO    MainThread:3619015 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-09 03:44:09,182 INFO    MainThread:3619015 [wandb_init.py:init():803] backend started and connected
2025-03-09 03:44:09,183 INFO    MainThread:3619015 [wandb_init.py:init():896] updated telemetry
2025-03-09 03:44:09,184 INFO    MainThread:3619015 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-09 03:44:09,801 INFO    MainThread:3619015 [wandb_init.py:init():995] starting run threads in backend
2025-03-09 03:44:09,867 INFO    MainThread:3619015 [wandb_run.py:_console_start():2377] atexit reg
2025-03-09 03:44:09,867 INFO    MainThread:3619015 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 03:44:09,867 INFO    MainThread:3619015 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 03:44:09,867 INFO    MainThread:3619015 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-09 03:44:09,868 INFO    MainThread:3619015 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-09 03:44:10,901 INFO    MainThread:3619015 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=10
2025-03-09 03:44:11,681 WARNING MsgRouterThr:3619015 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-09 03:44:11,682 INFO    MsgRouterThr:3619015 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034413-h19ufxjz/logs/debug.log
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034413-h19ufxjz/logs/debug-internal.log
2025-03-09 03:44:13,606 INFO    Thread-4 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:13,607 INFO    Thread-4 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 128, 'epochs': 5, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-09 03:44:13,607 INFO    Thread-4 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:13,607 ERROR   Thread-4 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:13,616 INFO    Thread-4 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:17,161 INFO    Thread-5 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:17,161 INFO    Thread-5 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:17,161 INFO    Thread-5 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:17,161 INFO    Thread-5 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:17,162 INFO    Thread-5 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:17,162 INFO    Thread-5 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034417-uanivfkl/logs/debug.log
2025-03-09 03:44:17,162 INFO    Thread-5 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034417-uanivfkl/logs/debug-internal.log
2025-03-09 03:44:17,162 INFO    Thread-5 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:17,162 INFO    Thread-5 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_size': 32, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:17,162 INFO    Thread-5 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:17,162 ERROR   Thread-5 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:17,168 INFO    Thread-5 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034427-m12apsft/logs/debug.log
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034427-m12apsft/logs/debug-internal.log
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_size': 256, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 4, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:27,190 INFO    Thread-6 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:27,190 ERROR   Thread-6 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:27,194 INFO    Thread-6 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034428-v2a99l9i/logs/debug.log
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034428-v2a99l9i/logs/debug-internal.log
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 256, 'epochs': 10, 'hidden_size': 32, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:28,064 ERROR   Thread-7 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:28,068 INFO    Thread-7 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034438-mmiyq43q/logs/debug.log
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034438-mmiyq43q/logs/debug-internal.log
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 15, 'hidden_size': 256, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:38,090 ERROR   Thread-8 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:38,094 INFO    Thread-8 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034439-edklxtow/logs/debug.log
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034439-edklxtow/logs/debug-internal.log
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:39,023 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_size': 256, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:39,023 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:39,023 ERROR   Thread-9 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:39,027 INFO    Thread-9 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:49,048 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034449-qfq4nw6b/logs/debug.log
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034449-qfq4nw6b/logs/debug-internal.log
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 15, 'hidden_size': 256, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:49,049 ERROR   Thread-10 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:49,053 INFO    Thread-10 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034450-vydjyd1f/logs/debug.log
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034450-vydjyd1f/logs/debug-internal.log
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_size': 32, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-09 03:44:50,163 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:50,163 ERROR   Thread-11 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:50,167 INFO    Thread-11 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034500-obquwryv/logs/debug.log
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034500-obquwryv/logs/debug-internal.log
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:45:00,190 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:45:00,190 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:45:00,190 ERROR   Thread-12 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:45:00,194 INFO    Thread-12 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034501-jeisgfqs/logs/debug.log
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034501-jeisgfqs/logs/debug-internal.log
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:45:01,062 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-09 03:45:01,062 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:45:01,062 ERROR   Thread-13 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:45:01,066 INFO    Thread-13 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:45:01,080 INFO    MainThread:3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
